-- =========================================================================
-- 中興新村省府生活色譜 - submissions（分享店家）資料表建置語法
-- 
-- 請將以下整段複製，並在 Supabase 管理後台左側選單的「SQL Editor」中
-- 開啟一個新的 Query (New query)，貼上後點擊執行 (Run)。
-- =========================================================================

-- 1. 建立 submissions 表格
CREATE TABLE public.submissions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    shop_name text not null,
    shop_location text,
    reason text,
    provider_name text,
    provider_contact text,
    notes text,
    status text default 'pending'::text
);

-- 2. 開源安全性：針對表格開啟「資料列層級安全性 (RLS)」
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- 3. 設定原則 (Policy)：允許前端的匿名訪客 (anon) 進行「送出寫入 (INSERT)」的動作
CREATE POLICY "允許匿名新增" 
ON public.submissions
FOR INSERT
TO anon
WITH CHECK (true);

-- 4. 設定原則 (Policy)：隱藏其他人看到的投稿內容，保障隱私。只允許寫入而隱藏讀取 (SELECT)
CREATE POLICY "禁止匿名讀取" 
ON public.submissions
FOR SELECT
TO anon
USING (false);

